# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # Deploy
  deploy:
    docker:
      - image: 'cimg/aws:2023.03'
    environment:
      REPO_HOST: 537534971119.dkr.ecr.us-east-1.amazonaws.com
      CONTAINER_NAME: soil-sampling
      CLUSTER: soil-sampling-prod
      REGION: us-east-1
      SERVICE: soil-sampling-prod
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: docker build -t ${CONTAINER_NAME} -f Dockerfile .
      - run:
          name: Login to ECR
          command: aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${REPO_HOST}
      - run:
          name: Tag builded image
          command: docker tag ${CONTAINER_NAME}:latest ${REPO_HOST}/${CONTAINER_NAME}:prod
      - run:
          name: Push to ECR
          command: docker push ${REPO_HOST}/${CONTAINER_NAME}:prod
      - run:
          command: aws ecs update-service --region ${REGION} --cluster ${CLUSTER} --service ${SERVICE} --force-new-deployment

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - approve-deploy:
          type: approval
      - deploy:
          requires:
            - approve-deploy
