export const SET_ALGO = "SET_ALGO";
export const SET_SAMPLE_AREA = "SET_SAMPLE_AREA";
export const SET_N_POINTS = "SET_N_POINTS";
export const SET_FIELD_POLYGONS = "SET_FIELD_POLYGONS";
export const SET_FIELD_POINTS = "SET_FIELD_POINTS";
export const SET_FIELD_MUKEYS = "SET_FIELD_MUKEYS";
export const SET_VIEWPORT = "SET_VIEWPORT";

// Triggers
export const REFRESH_POINTS = "REFRESH_POINTS";
export const DELETE_FEATURE = "DELETE_FEATURE";
