export const SET_ALGO = "SET_ALGO";
export const SET_SAMPLE_AREA = "SET_SAMPLE_AREA";
export const SET_N_POINTS = "SET_N_POINTS";
export const DELETE_DRAWN_POLYGON = "DELETE_DRAWN_POLYGON";
export const SET_DRAWN_POLYGONS = "SET_DRAWN_POLYGONS";
export const SET_VIEWPORT = "SET_VIEWPORT";
